<?php

return [
    'username-required' => 'Необходимо указать имя пользователя или адрес электронной почты.',
    'password-required' => 'Введите пароль вашей учетной записи.',
    'email-required' => 'Для продолжения необходимо указать действительный адрес электронной почты.',

    'login-title' => 'Войдите, чтобы продолжить',

    'username-label' => 'Имя пользователя или адрес электронной почты',
    'password-label' => 'Пароль',

    'login-button' => 'Авторизоваться',
    'return' => 'Вернуться к входу',

    'forgot-password' => [
        'title' => 'Запросить сброс пароля',
        'label' => 'Забыли пароль?',
        'email-label' => 'Почта',
        'email-content' => 'Введите адрес электронной почты вашей учетной записи, чтобы получить инструкции по сбросу пароля.',
        'send-email' => 'Отправить электронное письмо',
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery-code' => 'Recovery Code',
        'auth-code' => 'Authentication Code',
        'is-missing' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'is-not-missing' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost-device' => 'I\'ve Lost My Device',
        'not-lost-device' => 'I Have My Device',

    ],

    'reset-password' => [
        'new-required' => 'A new password is required.',
        'min-required' => 'Your new password should be at least 8 characters in length.',
        'no-match' => 'Your new password does not match.',
        'email-label' => 'Email',
        'new-label' => 'New Password',
        'min-length' => 'Passwords must be at least 8 characters in length.',
        'confirm-label' => 'Confirm New Password',
        'label' => 'Reset Password',
    ],
    
    'failed' => 'No account matching those credentials could be found.',

    'two_factor' => [
        'label' => '2-Factor Token',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token was invalid.',
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Password must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
];
